sudo: required
services:
 - docker
language: php
php:
  - 5.6
cache:
  - apt

addons:
  firefox: "51.0.1"
  apt:
    packages:
      - nginx
      - realpath
env:
  DOCKER_COMPOSE_VERSION: 1.9.0
matrix:
  include:
    - php: 5.6
      env: RUN_LINTS=true

before_install: bash -xe travis/before-install.sh

install: bash -xe travis/install.sh

script: bash -xe travis/test-script.sh
